### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by youyoubilly** [FelixGSE/pypiano#4]
Hi! I got this error, how could i fix it?
Thanks!

from pypiano import Piano

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-04698afc6961> in <module>
----> 1 from pypiano import Piano

~/projects/pypiano/pypiano/__init__.py in <module>
----> 1 from .piano import Piano
      2 
      3 __all__ = ["pypiano"]

~/projects/pypiano/pypiano/piano.py in <module>
     12 from typing import Union
     13 from pathlib import Path
---> 14 from .keyboard import PianoKeyboard, PianoKey
     15 
     16 from .utils import (

~/projects/pypiano/pypiano/keyboard.py in <module>
    168 
    169 
--> 170 class PianoKeyboard(object):
    171     """Class representing a 88 key piano keyboard"""
    172 

~/projects/pypiano/pypiano/keyboard.py in PianoKeyboard()
    269 
    270     @property
--> 271     def distinct_key_names(self) -> set[str]:
    272         """Get all distinct key names / note names on the piano keyboard
    273 

TypeError: 'type' object is not subscriptable

**Comment by FelixGSE** [comment]
Hi, I am having trouble to reproduce your error. Can you provide a little bit more context on what you did?

**Comment by PaulShiLi** [comment]
Same error occurs when using example on replit.com

![image](https://user-images.githubusercontent.com/74270733/136642351-b9db8e16-01e2-4d8c-aa9e-7e3fa83da323.png)

**Comment by FelixGSE** [comment]
Hi guys, sorry for the long response time. I didn't have time to look into the issue earlier. It should be resolved now. I am a bit confused why I was not running into the same problem. Anyway, sorry again that it took so long.
